name: doom-rlhf
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.9.7
  - pip
  - tensorflow-deps
  - ipykernel

  ## PyPI packages
  - pip:
    - gym==0.26.2
    - vizdoom==1.1.14
    - numpy==1.23.2
    - matplotlib==3.7.1
    - opencv_python==4.7.0.72
    - tensorflow-macos==2.12.0
    - tensorflow-metal==0.7.1
    - tensorflow_probability==0.19.0