name: doom-rlhf
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.9.7
  - pip
  - ipykernel
  - pytorch

  ## PyPI packages
  - pip:
    - gymnasium==0.29.0
    - vizdoom==1.1.14
    - numpy==1.23.2
    - opencv_python==4.7.0.72
    - matplotlib==3.7.1
    - stable-baselines3[extra]
    - tensorboard
    - torch-tb-profiler