name: doom-rlhf
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.9.7
  - pip
  - ipykernel
  - pytorch 
  - pytorch-cuda=11.7

  ## PyPI packages
  - pip:
    - argparse==1.4.0
    - tqdm==4.65.0
    - gymnasium==0.29.0
    - vizdoom==1.2.0
    - numpy==1.23.2
    - opencv_python==4.7.0.72
    - matplotlib==3.7.1
    - stable-baselines3[extra]
    - tensorboard
    - torch-tb-profiler
    - ipywidgets